version: "3"
services:
    web_front:
        container_name: web_front
        build:
            context: ./
            args:
                - VITE_CLERK_PUBLISHABLE_KEY=pk_test_c3RlYWR5LWhpcHBvLTM5LmNsZXJrLmFjY291bnRzLmRldiQ
                - VITE_BASE_API_URL=http://localhost:3000
        ports:
            - "80:80"
    video_api:
        container_name: video_api
        build: ./video_api
        ports:
            - "3000:3000"
